# Generated by Django 4.0 on 2023-06-22 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisprudencias',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_causa', models.CharField(max_length=1)),
                ('rol', models.CharField(max_length=20)),
                ('caratula', models.CharField(max_length=255)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('fecha_sentencia', models.DateField()),
                ('descriptores', models.TextField()),
                ('link_sentencia', models.CharField(max_length=255)),
                ('url_sentencia', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
                ('tribunal', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=2)),
                ('relacionada', models.CharField(max_length=255)),
                ('visitas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='valoresJudisprudencias',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idParametro', models.IntegerField()),
                ('idItemlista', models.IntegerField(null=True)),
                ('valor', models.CharField(max_length=255, null=True)),
                ('parametro', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255, null=True)),
                ('jurisprudencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='reto1.jurisprudencias')),
            ],
        ),
    ]
