# Generated by Django 4.0 on 2023-06-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reto1', '0002_alter_jurisprudencias_caratula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisprudencias',
            name='link_sentencia',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='jurisprudencias',
            name='tribunal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jurisprudencias',
            name='url_sentencia',
            field=models.CharField(max_length=700),
        ),
    ]
