# Generated by Django 4.0 on 2023-06-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reto1', '0003_alter_jurisprudencias_link_sentencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisprudencias',
            name='caratula',
            field=models.CharField(max_length=700),
        ),
    ]
