# Generated by Django 4.0 on 2023-06-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reto1', '0004_alter_jurisprudencias_caratula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisprudencias',
            name='nombre_proyecto',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='jurisprudencias',
            name='relacionada',
            field=models.CharField(max_length=700),
        ),
    ]
