# Generated by Django 4.0 on 2023-06-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reto1', '0006_alter_jurisprudencias_relacionada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoresjudisprudencias',
            name='valor',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
