# Generated by Django 4.0 on 2023-06-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='concesionesMaritimas',
            fields=[
                ('numero_id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_concesion', models.IntegerField()),
                ('tipo_de_concesion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=50)),
                ('numero_rs_ds', models.CharField(max_length=50)),
                ('tipo_tramite', models.CharField(max_length=100)),
                ('concersionario', models.CharField(max_length=100)),
                ('tipo_vigencia', models.CharField(max_length=100)),
            ],
        ),
    ]
