# Generated by Django 4.0 on 2023-06-21 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reto2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concesionesmaritimas',
            name='fecha_creacion_dato',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='concesionesmaritimas',
            name='lugar',
            field=models.CharField(max_length=100),
        ),
    ]
