# Generated by Django 4.0 on 2023-06-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reto2', '0003_alter_concesionesmaritimas_concersionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concesionesmaritimas',
            name='comuna',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='concesionesmaritimas',
            name='tipo_de_concesion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='concesionesmaritimas',
            name='tipo_tramite',
            field=models.CharField(max_length=200),
        ),
    ]
